variable "name" {}
variable "location" {}
variable "rgn" {}
variable "computernameprefix" {}
variable "admin_user" {}
variable "admin_password" {}
variable "networkprofilename" {}
variable "lbbe" {}
variable "subnet" {}
#variables for data.tf
variable "db_user" {}
variable "db_password" {}
variable "db_name" {}
variable "db_adres" {}
variable "file_share_name" {}
variable "storage_account_key" {}
variable "storage_account_name" {}
variable "userdata" {}